INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (17, 'ZZZ111', 'Денис Колобков', 3, 'C2', 230.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (18, '234444', 'Иван Старовойтов', 3, 'D1', 180.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (19, 'LLLL12', 'Людмила Старовойтова', 3, 'D2', 224.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (20, 'RT34TR', 'Степан Дор', 4, 'A1', 129.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (21, '999666', 'Анастасия Шепелева', 4, 'A2', 152.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (22, '234444', 'Иван Старовойтов', 4, 'B1', 140.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (23, 'LLLL12', 'Людмила Старовойтова', 4, 'B2', 140.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (24, 'LLLL12', 'Роман Дронов', 4, 'D2', 109.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (25, '112233', 'Иван Иванов', 5, 'C2', 170.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (26, 'NNNBV2', 'Лариса Тельникова', 5, 'C1', 185.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (27, 'DSAS86', 'Лариса Привольная', 5, 'A1', 204.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (28, 'DSAS83', 'Артур Мирный', 5, 'B1', 189.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (29, 'DSAS81', 'Евгений Кудрявцев', 6, 'A1', 204.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (30, 'EE2344', 'Дмитрий Трусцов', 6, 'A2', 214.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (31, 'AS23PP', 'Максим Консомольцев', 6, 'B2', 176.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (32, '112233', 'Иван Иванов', 6, 'B1', 135.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (33, '309623', 'Татьяна Крот', 6, 'C1', 155.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (1, '112233', 'Иван Иванов', 5, 'C2', 170.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (2, 'BAMBAMBAM', 'Kizaru', 5, 'C2', 170.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (3, 'BAMBAMBAM', 'Kizaru', 5, 'C2', 170.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (4, 'BAMBAMBAM', 'Kizaru', 5, 'C2', 170.00);
INSERT INTO public.tickets (id, passport_number, passenger_name, flight_id, seat_number, cost) VALUES (5, 'BAMBAMBAM', 'Kizaru', 5, '546B', 170.00);
